ofrak_core/ofrak/gui/server.py, ofrak_core/ofrak/service/script_builder.py
=> Add root cache

frontend/src/App.svelte, frontend/src/ResourceTreeToolbar.svelte, frontend/src/ResourceTreeView.svelte, frontend/src/ScriptView.svelte, frontend/src/ofrak/remote_resource.js, frontend/src/stores.js
Add pane to gui that displays script to the user.
=> Add script gui pane

frontend/package.json, frontend/public/code.css, frontend/src/App.svelte, frontend/src/ScriptView.svelte
=> Add initial syntax highlighting

frontend/package.json, frontend/src/ResourceTreeToolbar.svelte, frontend/src/ScriptView.svelte, frontend/src/ofrak/remote_resource.js, frontend/src/ofrak/resource.js, ofrak_core/ofrak/gui/server.py, ofrak_core/ofrak/service/script_builder.py
=> Fix CSS and some lint stuff

frontend/src/ComponentConfig.svelte, frontend/src/Components.svelte, frontend/src/ResourceTreeToolbar.svelte, frontend/src/ofrak/remote_resource.js, frontend/src/ofrak/resource.js, ofrak_core/ofrak/gui/server.py, ofrak_core/test_ofrak/unit/test_ofrak_server.py
=> Add initial component + config support to frontend

ofrak_core/ofrak/gui/server.py
=> Add orjson back, remove debug print

frontend/src/App.svelte, frontend/src/ofrak/remote_resource.js, frontend/src/ofrak/resource.js, ofrak_core/ofrak/cli/command/gui.py, ofrak_core/ofrak/gui/script_builder.py, ofrak_core/ofrak/gui/server.py
=> Fixes based on PR feedback

ofrak_core/ofrak/gui/script_builder.py, ofrak_core/ofrak/gui/server.py
=> Updates from feedback, plus add json import back

ofrak_core/ofrak/gui/script_builder.py
=> Slightly more sane ordering of methods

frontend/src/ComponentsView.svelte, frontend/src/ofrak/remote_resource.js, frontend/src/ofrak/resource.js, ofrak_core/ofrak/gui/server.py
=> Add filtering to Run Components

ofrak_core/ofrak/gui/script_builder.py, ofrak_core/ofrak/gui/server.py
=> Apply changes to feedback

ofrak_core/ofrak/gui/script_builder.py
=> Fill out comments on public methods

frontend/src/ComponentsView.svelte
=> Modify css on component filter

frontend/src/ofrak/remote_resource.js, ofrak_core/ofrak/gui/script_builder.py, ofrak_core/ofrak/gui/server.py
=> Ensure actions update script, fix up doc strings

frontend/src/ofrak/remote_resource.js, ofrak_core/ofrak/gui/script_builder.py, ofrak_core/ofrak/gui/server.py
=> Fix up comments, hex strings, update on delete

ofrak_core/ofrak/gui/script_builder.py
=> Select on vaddr

ofrak_core/ofrak/gui/server.py
=> Make add_action last step in route handlers

ofrak_core/ofrak/gui/script_builder.py
=> Handle SelectableAttrErr in add_variable

ofrak_core/ofrak/gui/script_builder.py, ofrak_core/ofrak/gui/server.py
=> Make MyPy happy

ofrak_core/ofrak/gui/script_builder.py, ofrak_core/test_ofrak/unit/test_ofrak_server.py
=> Remove unused methods, add get_script test

ofrak_tutorial/notebooks_with_outputs/4_simple_code_modification.ipynb, ofrak_tutorial/notebooks_with_outputs/5_filesystem_modification.ipynb
=> Revert notebook files

ofrak_core/ofrak/gui/script_builder.py
=> Improve error message in script

ofrak_core/test_ofrak/unit/test_ofrak_server.py
=> Add test case for selectable attr err

ofrak_core/Dockerstub
=> Revert Dockerstub

ofrak_core/ofrak/gui/script_builder.py, ofrak_core/ofrak/gui/server.py
=> Make MyPy happy again

ofrak_core/ofrak/gui/script_builder.py
=> Remove unnecessary call to hex()

ofrak_core/ofrak/gui/script_builder.py, ofrak_core/ofrak/gui/server.py, ofrak_core/test_ofrak/unit/test_ofrak_server.py
=> Minor formatting/accuracy changes

ofrak_core/test_ofrak/unit/test_ofrak_server.py
=> Add clear queue test - this is currently failing

ofrak_core/ofrak/gui/script_builder.py, ofrak_core/test_ofrak/unit/test_ofrak_server.py
=> Clean up test cases

frontend/src/ofrak/remote_resource.js, ofrak_core/ofrak/gui/script_builder.py, ofrak_core/ofrak/gui/server.py
=> Some small fixes after merging

frontend/src/ScriptView.svelte, frontend/src/StartView.svelte, ofrak_core/ofrak/gui/script_builder.py, ofrak_core/ofrak/gui/server.py, ofrak_core/test_ofrak/unit/test_ofrak_server.py
=> Changes from latest feedback

frontend/src/ScriptView.svelte, frontend/src/StartView.svelte, ofrak_core/ofrak/gui/script_builder.py
=> Revert onMount, add a few missing type hints

ofrak_core/test_ofrak/unit/test_ofrak_server.py
=> Add requested comment to normalize test cases

frontend/src/App.svelte, frontend/src/BinaryModifyView.svelte, frontend/src/ComponentConfig.svelte, frontend/src/ComponentConfigNode.svelte, frontend/src/FindReplaceView.svelte, frontend/src/ResourceTreeNode.svelte, frontend/src/ResourceTreeToolbar.svelte, frontend/src/ofrak/remote_resource.js, ofrak_core/ofrak/gui/server.py, ofrak_core/test_ofrak/unit/test_ofrak_server.py
=> Improve component visuals

frontend/src/ComponentConfigNode.svelte, ofrak_core/ofrak/gui/server.py, ofrak_core/ofrak/ofrak_context.py, ofrak_patch_maker/ofrak_patch_maker/toolchain/abstract.py
=> working toolchain selection in frontend

frontend/src/ProjectManager/ProjectManagerAddFileToProject.svelte, frontend/src/ProjectManager/ProjectManagerSelector.svelte, frontend/src/ProjectManager/ProjectManagerToolbar.svelte, frontend/src/ProjectManager/ProjectManagerView.svelte, frontend/src/StartView.svelte, ofrak_core/ofrak/gui/server.py, ofrak_core/ofrak/project/project.py
=> Add project metadata and save option

frontend/src/StartView.svelte, frontend/src/stores.js, ofrak_core/CHANGELOG.md, ofrak_core/mypy.ini, ofrak_core/ofrak/core/__init__.py, ofrak_core/ofrak/core/extfs.py, ofrak_core/ofrak/core/ihex.py, ofrak_core/requirements.txt, ofrak_core/test_ofrak/components/assets/ext2.1024.img, ofrak_core/test_ofrak/components/assets/ext2.2048.img, ofrak_core/test_ofrak/components/assets/ext2.4096.img, ofrak_core/test_ofrak/components/assets/ext3.1024.img, ofrak_core/test_ofrak/components/assets/ext3.2048.img, ofrak_core/test_ofrak/components/assets/ext3.4096.img, ofrak_core/test_ofrak/components/assets/ext4.1024.img, ofrak_core/test_ofrak/components/assets/ext4.2048.img, ofrak_core/test_ofrak/components/assets/ext4.4096.img, ofrak_core/test_ofrak/components/assets/hello_world.ihex, ofrak_core/test_ofrak/components/assets/patch_demo.ihex, ofrak_core/test_ofrak/components/test_extfs_component.py, ofrak_core/test_ofrak/components/test_ihex.py
=> Merge latest master in 
